import './globals.css';

import type { Metadata } from 'next';
import type { PropsWithChildren } from 'react';
import { AppProviders } from '@/app/providers';

export const metadata: Metadata = {
  title: {
    default: "next",
    template: "%s | next",
  },
  description: "next generated by generator-t-generator.",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
